<a href="https://colab.research.google.com/github/striderssoftware/TensorFlow/blob/main/CSV%20Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd
import numpy as np


print ("strider was here:START")

# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
from tensorflow.keras import layers

abalone_train = pd.read_csv(
    "https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",
    names=["Length", "Diameter", "Height", "Whole weight", "Shucked weight",
           "Viscera weight", "Shell weight", "AnyKey"])

abalone_train.head()


abalone_features = abalone_train.copy()
abalone_labels = abalone_features.pop('AnyKey')

abalone_features = np.array(abalone_features)
print (abalone_features )

abalone_model = tf.keras.Sequential([
  layers.Dense(64),
  layers.Dense(1)
])

abalone_model.compile(loss = tf.keras.losses.MeanSquaredError(),
                      optimizer = tf.keras.optimizers.Adam())

abalone_model.fit(abalone_features, abalone_labels, epochs=10)

print ("END")


strider was here:START
[[0.435 0.335 0.11  ... 0.136 0.077 0.097]
 [0.585 0.45  0.125 ... 0.354 0.207 0.225]
 [0.655 0.51  0.16  ... 0.396 0.282 0.37 ]
 ...
 [0.53  0.42  0.13  ... 0.374 0.167 0.249]
 [0.395 0.315 0.105 ... 0.118 0.091 0.119]
 [0.45  0.355 0.12  ... 0.115 0.067 0.16 ]]
Epoch 1/10
104/104 [==============================] - 1s 3ms/step - loss: 65.6683
Epoch 2/10
104/104 [==============================] - 0s 2ms/step - loss: 12.4880
Epoch 3/10
104/104 [==============================] - 0s 2ms/step - loss: 8.7664
Epoch 4/10
104/104 [==============================] - 0s 2ms/step - loss: 8.2069
Epoch 5/10
104/104 [==============================] - 0s 2ms/step - loss: 7.7223
Epoch 6/10
104/104 [==============================] - 0s 2ms/step - loss: 7.3137
Epoch 7/10
104/104 [==============================] - 0s 2ms/step - loss: 7.0169
Epoch 8/10
104/104 [==============================] - 0s 2ms/step - loss: 6.7784
Epoch 9/10
104/104 [==============================] - 0s 2ms/st